# Generated by Django 4.0 on 2022-03-11 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='contact_person',
            new_name='contact_first_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
