# Generated by Django 4.0.3 on 2022-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_rename_business_name_lead_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(),
        ),
    ]
