# Generated by Django 4.0.3 on 2022-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_remove_note_subject_alter_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('newlead', 'New'), ('contacted', 'Contacted'), ('demostart', 'Demo scheduled'), ('demodone', 'Demo completed'), ('appstart', 'Application Sent'), ('appdone', 'Application Signed'), ('probation', 'Probation'), ('client', 'Client')], default='newlead', max_length=25),
        ),
    ]
